### ISSUE TITLE
[TODO] Missing

### ISSUE THREAD

**Issue by ssalv** [salvatorecriscioneweb/cockpit-EmailOnUserSave#1]
- [x] Settings UI
- [x] Logic
- [x] Events
- [x] Patch Accounts's Controllers
- [x] Send Email
- [ ] Fix README
- [ ] Upload better screenshots
- [ ] Check if there's any way to avoid patch accounts's controller ( it's ugly )
